// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repositories.Data;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(FashionDbContext))]
    [Migration("20260207101738_AddFollowTable")]
    partial class AddFollowTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ItemCategory", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.HasKey("ItemId", "CategoryId")
                        .HasName("Item_Category_pkey");

                    b.HasIndex("CategoryId");

                    b.ToTable("Item_Category", "fashion_db");
                });

            modelBuilder.Entity("Repositories.Entities.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountId"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar");

                    b.Property<DateTime?>("CodeExpiredAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("code_expires_at");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.Property<string>("VerificationCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("verification_code");

                    b.HasKey("AccountId")
                        .HasName("Account_pkey");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "Account_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "Account_username_key")
                        .IsUnique();

                    b.ToTable("Account", "fashion_db");
                });

            modelBuilder.Entity("Repositories.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category_name");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.HasKey("CategoryId")
                        .HasName("Category_pkey");

                    b.ToTable("Category", "fashion_db");
                });

            modelBuilder.Entity("Repositories.Entities.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("comment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommentId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("post_id");

                    b.HasKey("CommentId")
                        .HasName("Comment_pkey");

                    b.HasIndex("AccountId");

                    b.HasIndex("PostId");

                    b.ToTable("Comment", "fashion_db");
                });

            modelBuilder.Entity("Repositories.Entities.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_time");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("EventId")
                        .HasName("Events_pkey");

                    b.HasIndex("CreatorId");

                    b.ToTable("Events", "fashion_db");
                });

            modelBuilder.Entity("Repositories.Entities.ExpertFile", b =>
                {
                    b.Property<int>("ExpertFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("expert_file_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExpertFileId"));

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<string>("CertificateUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("certificate_url");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("integer")
                        .HasColumnName("experience_years");

                    b.Property<int>("ExpertProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("expert_profile_id");

                    b.Property<string>("LicenseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("license_url");

                    b.Property<double?>("RatingAvg")
                        .HasColumnType("double precision")
                        .HasColumnName("rating_avg");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<bool?>("Verified")
                        .HasColumnType("boolean")
                        .HasColumnName("verified");

                    b.HasKey("ExpertFileId")
                        .HasName("Expert_File_pkey");

                    b.HasIndex(new[] { "ExpertProfileId" }, "Expert_File_expert_profile_id_key")
                        .IsUnique();

                    b.ToTable("Expert_File", "fashion_db");
                });

            modelBuilder.Entity("Repositories.Entities.ExpertProfile", b =>
                {
                    b.Property<int>("ExpertProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("expert_profile_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExpertProfileId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExpertiseField")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("expertise_field");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool?>("Verified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("verified");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("integer")
                        .HasColumnName("years_of_experience");

                    b.HasKey("ExpertProfileId")
                        .HasName("Expert_Profile_pkey");

                    b.HasIndex(new[] { "AccountId" }, "Expert_Profile_account_id_key")
                        .IsUnique();

                    b.ToTable("Expert_Profile", "fashion_db");
                });

            modelBuilder.Entity("Repositories.Entities.Follow", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("FollowerId")
                        .HasColumnType("integer")
                        .HasColumnName("follower_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "FollowerId")
                        .HasName("Follow_pkey");

                    b.HasIndex("FollowerId");

                    b.ToTable("Follow", "fashion_db");
                });

            modelBuilder.Entity("Repositories.Entities.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroupId"));

                    b.Property<int?>("CreateBy")
                        .HasColumnType("integer")
                        .HasColumnName("create_by");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool?>("IsGroup")
                        .HasColumnType("boolean")
                        .HasColumnName("isGroup");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("GroupId")
                        .HasName("Group_pkey");

                    b.ToTable("Group", "fashion_db");
                });

            modelBuilder.Entity("Repositories.Entities.GroupUser", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("joined_at");

                    b.HasKey("GroupId", "AccountId")
                        .HasName("GroupUser_pkey");

                    b.HasIndex("AccountId");

                    b.ToTable("GroupUser", "fashion_db");
                });

            modelBuilder.Entity("Repositories.Entities.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("image_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImageId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("owner_type");

                    b.HasKey("ImageId")
                        .HasName("Images_pkey");

                    b.HasIndex("OwnerId");

                    b.ToTable("Images", "fashion_db");
                });

            modelBuilder.Entity("Repositories.Entities.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Brand")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("brand");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Fabric")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fabric");

                    b.Property<string>("ItemName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("item_name");

                    b.Property<string>("MainColor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("main_color");

                    b.Property<string>("Pattern")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("pattern");

                    b.Property<string>("Placement")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("placement");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Style")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("style");

                    b.Property<double?>("StyleScore")
                        .HasColumnType("double precision")
                        .HasColumnName("style_score");

                    b.Property<string>("Texture")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("texture");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.Property<int>("WardrobeId")
                        .HasColumnType("integer")
                        .HasColumnName("wardrobe_id");

                    b.HasKey("ItemId")
                        .HasName("Item_pkey");

                    b.HasIndex("WardrobeId");

                    b.ToTable("Item", "fashion_db");
                });

            modelBuilder.Entity("Repositories.Entities.MessReaction", b =>
                {
                    b.Property<int>("ReactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("react_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReactId"));

                    b.Property<int?>("AccountReactId")
                        .HasColumnType("integer")
                        .HasColumnName("account_react_id");

                    b.Property<int?>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    b.Property<string>("Type")
                        .HasColumnType("character varying")
                        .HasColumnName("type");

                    b.HasKey("ReactId")
                        .HasName("MessReaction_pkey");

                    b.HasIndex("AccountReactId");

                    b.HasIndex("MessageId");

                    b.ToTable("MessReaction", "fashion_db");
                });

            modelBuilder.Entity("Repositories.Entities.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<bool?>("IsRecalled")
                        .HasColumnType("boolean")
                        .HasColumnName("isRecalled");

                    b.Property<int?>("ReplyToMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("replyToMessage_id");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sentAt");

                    b.HasKey("MessageId")
                        .HasName("Message_pkey");

                    b.HasIndex("AccountId");

                    b.HasIndex("GroupId");

                    b.HasIndex("ReplyToMessageId");

                    b.ToTable("Message", "fashion_db");
                });

            modelBuilder.Entity("Repositories.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("notification_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_id");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("NotificationId")
                        .HasName("Notification_pkey");

                    b.HasIndex("SenderId");

                    b.ToTable("Notification", "fashion_db");
                });

            modelBuilder.Entity("Repositories.Entities.Outfit", b =>
                {
                    b.Property<int>("OutfitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("outfit_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OutfitId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("OutfitName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("outfit_name");

                    b.HasKey("OutfitId")
                        .HasName("Outfit_pkey");

                    b.HasIndex("AccountId");

                    b.ToTable("Outfit", "fashion_db");
                });

            modelBuilder.Entity("Repositories.Entities.Package", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("package_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PackageId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<int>("CoinAmount")
                        .HasColumnType("integer")
                        .HasColumnName("coin_amount");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("PriceVnd")
                        .HasColumnType("integer")
                        .HasColumnName("price_vnd");

                    b.HasKey("PackageId")
                        .HasName("Package_pkey");

                    b.HasIndex("AccountId");

                    b.ToTable("Package", "fashion_db");
                });

            modelBuilder.Entity("Repositories.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("payment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("order_code");

                    b.Property<int?>("PackageId")
                        .HasColumnType("integer")
                        .HasColumnName("package_id");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("PaymentId")
                        .HasName("Payment_pkey");

                    b.HasIndex("AccountId");

                    b.HasIndex("PackageId");

                    b.ToTable("Payment", "fashion_db");
                });

            modelBuilder.Entity("Repositories.Entities.Photo", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("photo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PhotoId"));

                    b.Property<int?>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("character varying")
                        .HasColumnName("photo_url");

                    b.HasKey("PhotoId")
                        .HasName("Photos_pkey");

                    b.HasIndex("MessageId");

                    b.ToTable("Photos", "fashion_db");
                });

            modelBuilder.Entity("Repositories.Entities.PinnedMessage", b =>
                {
                    b.Property<int>("PinnedMsgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pinnedMsg_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PinnedMsgId"));

                    b.Property<int?>("AccountPinnedId")
                        .HasColumnType("integer")
                        .HasColumnName("accountPinned_id");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<int?>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    b.Property<DateTime?>("PinnedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("pinned_at");

                    b.HasKey("PinnedMsgId")
                        .HasName("PinnedMessage_pkey");

                    b.HasIndex("AccountPinnedId");

                    b.HasIndex("GroupId");

                    b.HasIndex("MessageId");

                    b.ToTable("PinnedMessage", "fashion_db");
                });

            modelBuilder.Entity("Repositories.Entities.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("post_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PostId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    b.Property<bool?>("IsExpertPost")
                        .HasColumnType("boolean")
                        .HasColumnName("is_expert_post");

                    b.Property<int?>("LikeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("like_count");

                    b.Property<double?>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<int?>("ShareCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("share_count");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Tittle")
                        .HasColumnType("text")
                        .HasColumnName("tittle");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PostId")
                        .HasName("Post_pkey");

                    b.HasIndex("AccountId");

                    b.HasIndex("EventId");

                    b.ToTable("Post", "fashion_db");
                });

            modelBuilder.Entity("Repositories.Entities.PostVector", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("post_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("VectorData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vector_data");

                    b.HasKey("PostId")
                        .HasName("Post_Vector_pkey");

                    b.ToTable("Post_Vector", "fashion_db");
                });

            modelBuilder.Entity("Repositories.Entities.Reaction", b =>
                {
                    b.Property<int>("ReactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("reaction_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReactionId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("post_id");

                    b.Property<string>("ReactionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("reaction_type");

                    b.HasKey("ReactionId")
                        .HasName("Reaction_pkey");

                    b.HasIndex("AccountId");

                    b.HasIndex("PostId");

                    b.ToTable("Reaction", "fashion_db");
                });

            modelBuilder.Entity("Repositories.Entities.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("refresh_token_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RefreshTokenId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceInfo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("device_info");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expiry_date");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ip_address");

                    b.Property<bool?>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("isAvailable");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token");

                    b.HasKey("RefreshTokenId")
                        .HasName("RefreshToken_pkey");

                    b.HasIndex(new[] { "AccountId" }, "RefreshToken_account_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "DeviceInfo" }, "RefreshToken_device_info_key")
                        .IsUnique();

                    b.HasIndex(new[] { "IpAddress" }, "RefreshToken_ip_address_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Token" }, "RefreshToken_token_key")
                        .IsUnique();

                    b.ToTable("RefreshToken", "fashion_db");
                });

            modelBuilder.Entity("Repositories.Entities.ReportType", b =>
                {
                    b.Property<int>("ReportTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("report_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type_name");

                    b.HasKey("ReportTypeId")
                        .HasName("Report_Type_pkey");

                    b.HasIndex(new[] { "TypeName" }, "Report_Type_type_name_key")
                        .IsUnique();

                    b.ToTable("Report_Type", "fashion_db");
                });

            modelBuilder.Entity("Repositories.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("Role_pkey");

                    b.HasIndex(new[] { "RoleName" }, "Role_role_name_key")
                        .IsUnique();

                    b.ToTable("Role", "fashion_db");
                });

            modelBuilder.Entity("Repositories.Entities.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("transaction_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<int>("AmountCoin")
                        .HasColumnType("integer")
                        .HasColumnName("amount_coin");

                    b.Property<int?>("BalanceAfter")
                        .HasColumnType("integer")
                        .HasColumnName("balance_after");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("PaymentId")
                        .HasColumnType("integer")
                        .HasColumnName("payment_id");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("integer")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("reference_type");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("TransactionId")
                        .HasName("Transaction_pkey");

                    b.HasIndex("AccountId");

                    b.HasIndex(new[] { "PaymentId" }, "Transaction_payment_id_key")
                        .IsUnique();

                    b.ToTable("Transaction", "fashion_db");
                });

            modelBuilder.Entity("Repositories.Entities.UserProfileVector", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AccountId")
                        .HasName("User_Profile_Vector_pkey");

                    b.ToTable("User_Profile_Vector", "fashion_db");
                });

            modelBuilder.Entity("Repositories.Entities.UserReport", b =>
                {
                    b.Property<int>("UserReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_report_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserReportId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("post_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<int>("ReportTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("report_type_id");

                    b.HasKey("UserReportId")
                        .HasName("User_Report_pkey");

                    b.HasIndex("AccountId");

                    b.HasIndex("PostId");

                    b.HasIndex("ReportTypeId");

                    b.ToTable("User_Report", "fashion_db");
                });

            modelBuilder.Entity("Repositories.Entities.Wardrobe", b =>
                {
                    b.Property<int>("WardrobeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("wardrobe_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WardrobeId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("WardrobeId")
                        .HasName("Wardrobe_pkey");

                    b.HasIndex(new[] { "AccountId" }, "Wardrobe_account_id_key")
                        .IsUnique();

                    b.ToTable("Wardrobe", "fashion_db");
                });

            modelBuilder.Entity("ItemCategory", b =>
                {
                    b.HasOne("Repositories.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("Item_Category_category_id_fkey");

                    b.HasOne("Repositories.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("Item_Category_item_id_fkey");
                });

            modelBuilder.Entity("Repositories.Entities.Account", b =>
                {
                    b.HasOne("Repositories.Entities.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("Account_role_id_fkey");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Repositories.Entities.Comment", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithMany("Comments")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("Comment_account_id_fkey");

                    b.HasOne("Repositories.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("Comment_post_id_fkey");

                    b.Navigation("Account");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Repositories.Entities.Event", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Creator")
                        .WithMany("Events")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("Events_creator_id_fkey");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Repositories.Entities.ExpertFile", b =>
                {
                    b.HasOne("Repositories.Entities.ExpertProfile", "ExpertProfile")
                        .WithOne("ExpertFile")
                        .HasForeignKey("Repositories.Entities.ExpertFile", "ExpertProfileId")
                        .IsRequired()
                        .HasConstraintName("Expert_File_expert_profile_id_fkey");

                    b.Navigation("ExpertProfile");
                });

            modelBuilder.Entity("Repositories.Entities.ExpertProfile", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithOne("ExpertProfile")
                        .HasForeignKey("Repositories.Entities.ExpertProfile", "AccountId")
                        .IsRequired()
                        .HasConstraintName("Expert_Profile_account_id_fkey");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Repositories.Entities.Follow", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Follower")
                        .WithMany("FollowFollowerNavigations")
                        .HasForeignKey("FollowerId")
                        .IsRequired()
                        .HasConstraintName("Follow_follower_id_fkey");

                    b.HasOne("Repositories.Entities.Account", "User")
                        .WithMany("FollowUserNavigations")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("Follow_user_id_fkey");

                    b.Navigation("Follower");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repositories.Entities.GroupUser", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithMany("GroupUsers")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("GroupUser_account_id_fkey");

                    b.HasOne("Repositories.Entities.Group", "Group")
                        .WithMany("GroupUsers")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("GroupUser_group_id_fkey");

                    b.Navigation("Account");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Repositories.Entities.Image", b =>
                {
                    b.HasOne("Repositories.Entities.Item", "Owner")
                        .WithMany("Images")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("Images_owner_id_fkey");

                    b.HasOne("Repositories.Entities.Post", "OwnerNavigation")
                        .WithMany("Images")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("Images_owner_id_fkey1");

                    b.Navigation("Owner");

                    b.Navigation("OwnerNavigation");
                });

            modelBuilder.Entity("Repositories.Entities.Item", b =>
                {
                    b.HasOne("Repositories.Entities.Wardrobe", "Wardrobe")
                        .WithMany("Items")
                        .HasForeignKey("WardrobeId")
                        .IsRequired()
                        .HasConstraintName("Item_wardrobe_id_fkey");

                    b.Navigation("Wardrobe");
                });

            modelBuilder.Entity("Repositories.Entities.MessReaction", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "AccountReact")
                        .WithMany("MessReactions")
                        .HasForeignKey("AccountReactId")
                        .HasConstraintName("MessReaction_account_react_id_fkey");

                    b.HasOne("Repositories.Entities.Message", "Message")
                        .WithMany("MessReactions")
                        .HasForeignKey("MessageId")
                        .HasConstraintName("MessReaction_message_id_fkey");

                    b.Navigation("AccountReact");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Repositories.Entities.Message", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithMany("Messages")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("Message_account_id_fkey");

                    b.HasOne("Repositories.Entities.Group", "Group")
                        .WithMany("Messages")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("Message_group_id_fkey");

                    b.HasOne("Repositories.Entities.Message", "ReplyToMessage")
                        .WithMany("InverseReplyToMessage")
                        .HasForeignKey("ReplyToMessageId")
                        .HasConstraintName("Message_replyToMessage_id_fkey");

                    b.Navigation("Account");

                    b.Navigation("Group");

                    b.Navigation("ReplyToMessage");
                });

            modelBuilder.Entity("Repositories.Entities.Notification", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Sender")
                        .WithMany("Notifications")
                        .HasForeignKey("SenderId")
                        .IsRequired()
                        .HasConstraintName("Notification_sender_id_fkey");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Repositories.Entities.Outfit", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithMany("Outfits")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("Outfit_account_id_fkey");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Repositories.Entities.Package", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithMany("Packages")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("Package_account_id_fkey");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Repositories.Entities.Payment", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithMany("Payments")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("Payment_account_id_fkey");

                    b.HasOne("Repositories.Entities.Package", "Package")
                        .WithMany("Payments")
                        .HasForeignKey("PackageId")
                        .HasConstraintName("Payment_package_id_fkey");

                    b.Navigation("Account");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Repositories.Entities.Photo", b =>
                {
                    b.HasOne("Repositories.Entities.Message", "Message")
                        .WithMany("Photos")
                        .HasForeignKey("MessageId")
                        .HasConstraintName("Photos_message_id_fkey");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Repositories.Entities.PinnedMessage", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "AccountPinned")
                        .WithMany("PinnedMessages")
                        .HasForeignKey("AccountPinnedId")
                        .HasConstraintName("PinnedMessage_accountPinned_id_fkey");

                    b.HasOne("Repositories.Entities.Group", "Group")
                        .WithMany("PinnedMessages")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("PinnedMessage_group_id_fkey");

                    b.HasOne("Repositories.Entities.Message", "Message")
                        .WithMany("PinnedMessages")
                        .HasForeignKey("MessageId")
                        .HasConstraintName("PinnedMessage_message_id_fkey");

                    b.Navigation("AccountPinned");

                    b.Navigation("Group");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Repositories.Entities.Post", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithMany("Posts")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("Post_account_id_fkey");

                    b.HasOne("Repositories.Entities.Event", "Event")
                        .WithMany("Posts")
                        .HasForeignKey("EventId")
                        .HasConstraintName("Post_event_id_fkey");

                    b.Navigation("Account");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Repositories.Entities.PostVector", b =>
                {
                    b.HasOne("Repositories.Entities.Post", "Post")
                        .WithOne("PostVector")
                        .HasForeignKey("Repositories.Entities.PostVector", "PostId")
                        .IsRequired()
                        .HasConstraintName("Post_Vector_post_id_fkey");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Repositories.Entities.Reaction", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithMany("Reactions")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("Reaction_account_id_fkey");

                    b.HasOne("Repositories.Entities.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("Reaction_post_id_fkey");

                    b.Navigation("Account");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Repositories.Entities.RefreshToken", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithOne("RefreshToken")
                        .HasForeignKey("Repositories.Entities.RefreshToken", "AccountId")
                        .IsRequired()
                        .HasConstraintName("RefreshToken_account_id_fkey");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Repositories.Entities.Transaction", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("Transaction_account_id_fkey");

                    b.HasOne("Repositories.Entities.Payment", "Payment")
                        .WithOne("Transaction")
                        .HasForeignKey("Repositories.Entities.Transaction", "PaymentId")
                        .IsRequired()
                        .HasConstraintName("Transaction_payment_id_fkey");

                    b.Navigation("Account");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Repositories.Entities.UserProfileVector", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithOne("UserProfileVector")
                        .HasForeignKey("Repositories.Entities.UserProfileVector", "AccountId")
                        .IsRequired()
                        .HasConstraintName("User_Profile_Vector_account_id_fkey");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Repositories.Entities.UserReport", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithMany("UserReports")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("User_Report_account_id_fkey");

                    b.HasOne("Repositories.Entities.Post", "Post")
                        .WithMany("UserReports")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("User_Report_post_id_fkey");

                    b.HasOne("Repositories.Entities.ReportType", "ReportType")
                        .WithMany("UserReports")
                        .HasForeignKey("ReportTypeId")
                        .IsRequired()
                        .HasConstraintName("User_Report_report_type_id_fkey");

                    b.Navigation("Account");

                    b.Navigation("Post");

                    b.Navigation("ReportType");
                });

            modelBuilder.Entity("Repositories.Entities.Wardrobe", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithOne("Wardrobe")
                        .HasForeignKey("Repositories.Entities.Wardrobe", "AccountId")
                        .IsRequired()
                        .HasConstraintName("Wardrobe_account_id_fkey");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Repositories.Entities.Account", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Events");

                    b.Navigation("ExpertProfile");

                    b.Navigation("FollowFollowerNavigations");

                    b.Navigation("FollowUserNavigations");

                    b.Navigation("GroupUsers");

                    b.Navigation("MessReactions");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("Outfits");

                    b.Navigation("Packages");

                    b.Navigation("Payments");

                    b.Navigation("PinnedMessages");

                    b.Navigation("Posts");

                    b.Navigation("Reactions");

                    b.Navigation("RefreshToken");

                    b.Navigation("Transactions");

                    b.Navigation("UserProfileVector");

                    b.Navigation("UserReports");

                    b.Navigation("Wardrobe");
                });

            modelBuilder.Entity("Repositories.Entities.Event", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Repositories.Entities.ExpertProfile", b =>
                {
                    b.Navigation("ExpertFile");
                });

            modelBuilder.Entity("Repositories.Entities.Group", b =>
                {
                    b.Navigation("GroupUsers");

                    b.Navigation("Messages");

                    b.Navigation("PinnedMessages");
                });

            modelBuilder.Entity("Repositories.Entities.Item", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Repositories.Entities.Message", b =>
                {
                    b.Navigation("InverseReplyToMessage");

                    b.Navigation("MessReactions");

                    b.Navigation("Photos");

                    b.Navigation("PinnedMessages");
                });

            modelBuilder.Entity("Repositories.Entities.Package", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Repositories.Entities.Payment", b =>
                {
                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Repositories.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Images");

                    b.Navigation("PostVector");

                    b.Navigation("Reactions");

                    b.Navigation("UserReports");
                });

            modelBuilder.Entity("Repositories.Entities.ReportType", b =>
                {
                    b.Navigation("UserReports");
                });

            modelBuilder.Entity("Repositories.Entities.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Repositories.Entities.Wardrobe", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
