// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using Repositories.Data;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(FashionDbContext))]
    partial class FashionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ItemCategory", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.HasKey("ItemId", "CategoryId")
                        .HasName("Item_Category_pkey");

                    b.HasIndex("CategoryId");

                    b.ToTable("Item_Category", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("role_name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_claim_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("claim_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AccountClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AccountLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AccountRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("token_name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("token_value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AccountTokens", (string)null);
                });

            modelBuilder.Entity("Repositories.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<DateTime?>("CodeExpiredAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("code_expires_at");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<int>("CountFollower")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("count_follower");

                    b.Property<int>("CountFollowing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("count_following");

                    b.Property<int>("CountPost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("count_post");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<int>("FreeTryOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("free_try_on");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.Property<string>("VerificationCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("verification_code");

                    b.HasKey("Id")
                        .HasName("Account_pkey");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Accounts", "public");
                });

            modelBuilder.Entity("Repositories.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category_name");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.HasKey("CategoryId")
                        .HasName("Category_pkey");

                    b.ToTable("Category", "public");
                });

            modelBuilder.Entity("Repositories.Entities.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("comment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommentId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("post_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("CommentId")
                        .HasName("comment_pkey");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_comment_account_id");

                    b.HasIndex("PostId")
                        .HasDatabaseName("IX_Comment_PostId");
                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_comment_post_id");

                    b.ToTable("Comment", "public");
                });

            modelBuilder.Entity("Repositories.Entities.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_time");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("EventId")
                        .HasName("Events_pkey");

                    b.HasIndex("CreatorId");

                    b.ToTable("Events", "public");
                });

            modelBuilder.Entity("Repositories.Entities.EventWinner", b =>
                {
                    b.Property<int>("EventWinnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventWinnerId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PrizeEventId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("EventWinnerId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("PrizeEventId")
                        .IsUnique();

                    b.ToTable("TheEventWinner", "public");
                });

            modelBuilder.Entity("Repositories.Entities.ExpertFile", b =>
                {
                    b.Property<int>("ExpertFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("expert_file_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExpertFileId"));

                    b.Property<string>("CertificateUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("certificate_url");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CvUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cv_url");

                    b.Property<int>("ExpertProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("expert_profile_id");

                    b.Property<string>("IdentityProofUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("identity_proof_url");

                    b.Property<string>("LicenseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("license_url");

                    b.Property<double?>("RatingAvg")
                        .HasColumnType("double precision")
                        .HasColumnName("rating_avg");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("ExpertFileId")
                        .HasName("Expert_File_pkey");

                    b.HasIndex(new[] { "ExpertProfileId" }, "Expert_File_expert_profile_id_key")
                        .IsUnique();

                    b.ToTable("Expert_File", "public");
                });

            modelBuilder.Entity("Repositories.Entities.ExpertProfile", b =>
                {
                    b.Property<int>("ExpertProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("expert_profile_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExpertProfileId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExpertiseField")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("expertise_field");

                    b.Property<string>("StyleAesthetic")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("style_aesthetic");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool?>("Verified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("verified");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("integer")
                        .HasColumnName("years_of_experience");

                    b.HasKey("ExpertProfileId")
                        .HasName("Expert_Profile_pkey");

                    b.HasIndex(new[] { "AccountId" }, "Expert_Profile_account_id_key")
                        .IsUnique();

                    b.ToTable("Expert_Profile", "public");
                });

            modelBuilder.Entity("Repositories.Entities.Follow", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("FollowerId")
                        .HasColumnType("integer")
                        .HasColumnName("follower_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "FollowerId")
                        .HasName("Follow_pkey");

                    b.HasIndex("FollowerId");

                    b.ToTable("Follow", "public");
                });

            modelBuilder.Entity("Repositories.Entities.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroupId"));

                    b.Property<int?>("CreateBy")
                        .HasColumnType("integer")
                        .HasColumnName("create_by");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool?>("IsGroup")
                        .HasColumnType("boolean")
                        .HasColumnName("isGroup");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("GroupId")
                        .HasName("Group_pkey");

                    b.ToTable("Group", "public");
                });

            modelBuilder.Entity("Repositories.Entities.GroupUser", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("joined_at");

                    b.HasKey("GroupId", "AccountId")
                        .HasName("GroupUser_pkey");

                    b.HasIndex("AccountId");

                    b.ToTable("GroupUser", "public");
                });

            modelBuilder.Entity("Repositories.Entities.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("image_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImageId"));

                    b.Property<int?>("AccountAvatarId")
                        .HasColumnType("integer")
                        .HasColumnName("account_avatar_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<int?>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<string>("OwnerType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("owner_type");

                    b.Property<int?>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("post_id");

                    b.HasKey("ImageId")
                        .HasName("Images_pkey");

                    b.HasIndex("AccountAvatarId");

                    b.HasIndex("ItemId");

                    b.HasIndex("PostId");

                    b.ToTable("Images", "public");
                });

            modelBuilder.Entity("Repositories.Entities.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Brand")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("brand");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Fabric")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fabric");

                    b.Property<Vector>("ItemEmbedding")
                        .IsRequired()
                        .HasColumnType("vector(768)")
                        .HasColumnName("item_embedding");

                    b.Property<string>("ItemName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("item_name");

                    b.Property<string>("MainColor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("main_color");

                    b.Property<string>("Pattern")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("pattern");

                    b.Property<string>("Placement")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("placement");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Style")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("style");

                    b.Property<double?>("StyleScore")
                        .HasColumnType("double precision")
                        .HasColumnName("style_score");

                    b.Property<string>("Texture")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("texture");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.Property<int>("WardrobeId")
                        .HasColumnType("integer")
                        .HasColumnName("wardrobe_id");

                    b.HasKey("ItemId")
                        .HasName("Item_pkey");

                    b.HasIndex("WardrobeId");

                    b.ToTable("Item", "public");
                });

            modelBuilder.Entity("Repositories.Entities.MessReaction", b =>
                {
                    b.Property<int>("ReactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("react_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReactId"));

                    b.Property<int?>("AccountReactId")
                        .HasColumnType("integer")
                        .HasColumnName("account_react_id");

                    b.Property<int?>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    b.Property<string>("Type")
                        .HasColumnType("character varying")
                        .HasColumnName("type");

                    b.HasKey("ReactId")
                        .HasName("MessReaction_pkey");

                    b.HasIndex("AccountReactId");

                    b.HasIndex("MessageId");

                    b.ToTable("MessReaction", "public");
                });

            modelBuilder.Entity("Repositories.Entities.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<bool?>("IsRecalled")
                        .HasColumnType("boolean")
                        .HasColumnName("isRecalled");

                    b.Property<int?>("ReplyToMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("replyToMessage_id");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sentAt");

                    b.HasKey("MessageId")
                        .HasName("Message_pkey");

                    b.HasIndex("AccountId");

                    b.HasIndex("GroupId");

                    b.HasIndex("ReplyToMessageId");

                    b.ToTable("Message", "public");
                });

            modelBuilder.Entity("Repositories.Entities.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("acc_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("img_url");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("AccountModels", "public");
                });

            modelBuilder.Entity("Repositories.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("notification_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_id");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("NotificationId")
                        .HasName("Notification_pkey");

                    b.HasIndex("SenderId");

                    b.ToTable("Notification", "public");
                });

            modelBuilder.Entity("Repositories.Entities.Outfit", b =>
                {
                    b.Property<int>("OutfitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("outfit_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OutfitId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("OutfitName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("outfit_name");

                    b.HasKey("OutfitId")
                        .HasName("Outfit_pkey");

                    b.HasIndex("AccountId");

                    b.ToTable("Outfit", "public");
                });

            modelBuilder.Entity("Repositories.Entities.Package", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("package_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PackageId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<int>("CoinAmount")
                        .HasColumnType("integer")
                        .HasColumnName("coin_amount");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("PriceVnd")
                        .HasColumnType("integer")
                        .HasColumnName("price_vnd");

                    b.HasKey("PackageId")
                        .HasName("Package_pkey");

                    b.HasIndex("AccountId");

                    b.ToTable("Package", "public");
                });

            modelBuilder.Entity("Repositories.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("payment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("order_code");

                    b.Property<int?>("PackageId")
                        .HasColumnType("integer")
                        .HasColumnName("package_id");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("PaymentId")
                        .HasName("Payment_pkey");

                    b.HasIndex("AccountId");

                    b.HasIndex("PackageId");

                    b.ToTable("Payment", "public");
                });

            modelBuilder.Entity("Repositories.Entities.Photo", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("photo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PhotoId"));

                    b.Property<int?>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("character varying")
                        .HasColumnName("photo_url");

                    b.HasKey("PhotoId")
                        .HasName("Photos_pkey");

                    b.HasIndex("MessageId");

                    b.ToTable("Photos", "public");
                });

            modelBuilder.Entity("Repositories.Entities.PinnedMessage", b =>
                {
                    b.Property<int>("PinnedMsgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pinnedMsg_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PinnedMsgId"));

                    b.Property<int?>("AccountPinnedId")
                        .HasColumnType("integer")
                        .HasColumnName("accountPinned_id");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<int?>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    b.Property<DateTime?>("PinnedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("pinned_at");

                    b.HasKey("PinnedMsgId")
                        .HasName("PinnedMessage_pkey");

                    b.HasIndex("AccountPinnedId");

                    b.HasIndex("GroupId");

                    b.HasIndex("MessageId");

                    b.ToTable("PinnedMessage", "public");
                });

            modelBuilder.Entity("Repositories.Entities.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("post_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PostId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    b.Property<bool?>("IsExpertPost")
                        .HasColumnType("boolean")
                        .HasColumnName("is_expert_post");

                    b.Property<int?>("LikeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("like_count");

                    b.Property<double?>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<int?>("ShareCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("share_count");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Tittle")
                        .HasColumnType("text")
                        .HasColumnName("tittle");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PostId")
                        .HasName("Post_pkey");

                    b.HasIndex("AccountId");

                    b.HasIndex("EventId");

                    b.ToTable("Post", "public");
                });

            modelBuilder.Entity("Repositories.Entities.PostVector", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("post_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("VectorData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vector_data");

                    b.HasKey("PostId")
                        .HasName("Post_Vector_pkey");

                    b.ToTable("Post_Vector", "public");
                });

            modelBuilder.Entity("Repositories.Entities.PrizeEvent", b =>
                {
                    b.Property<int>("PrizeEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("prize_event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PrizeEventId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    b.Property<string>("Ranked")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ranked");

                    b.Property<int>("RewardCoin")
                        .HasColumnType("integer")
                        .HasColumnName("reward_coin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("PrizeEventId");

                    b.HasIndex("EventId");

                    b.ToTable("PrizeEvent", "public");
                });

            modelBuilder.Entity("Repositories.Entities.Reaction", b =>
                {
                    b.Property<int>("ReactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("reaction_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReactionId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("post_id");

                    b.HasKey("ReactionId")
                        .HasName("reaction_pkey");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_reaction_account_id");

                    b.HasIndex("PostId");
                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_reaction_post_id");

                    b.HasIndex("AccountId", "PostId")
                        .IsUnique()
                        .HasDatabaseName("ux_reaction_account_post");

                    b.HasIndex(new[] { "AccountId", "PostId" }, "UQ_Account_Post_Reaction")
                        .IsUnique();

                    b.ToTable("Reaction", "public");
                });

            modelBuilder.Entity("Repositories.Entities.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("refresh_token_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RefreshTokenId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceInfo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("device_info");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expiry_date");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ip_address");

                    b.Property<bool?>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("isAvailable");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token");

                    b.HasKey("RefreshTokenId")
                        .HasName("RefreshToken_pkey");

                    b.HasIndex(new[] { "AccountId" }, "RefreshToken_account_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "DeviceInfo" }, "RefreshToken_device_info_key");

                    b.HasIndex(new[] { "IpAddress" }, "RefreshToken_ip_address_key");

                    b.HasIndex(new[] { "Token" }, "RefreshToken_token_key")
                        .IsUnique();

                    b.ToTable("RefreshToken", "public");
                });

            modelBuilder.Entity("Repositories.Entities.ReportType", b =>
                {
                    b.Property<int>("ReportTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("report_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type_name");

                    b.HasKey("ReportTypeId")
                        .HasName("Report_Type_pkey");

                    b.HasIndex(new[] { "TypeName" }, "Report_Type_type_name_key")
                        .IsUnique();

                    b.ToTable("Report_Type", "public");
                });

            modelBuilder.Entity("Repositories.Entities.Scoreboard", b =>
                {
                    b.Property<int>("ScoreboardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScoreboardId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Like")
                        .HasColumnType("integer");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<int>("Share")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ScoreboardId");

                    b.HasIndex("PostId")
                        .IsUnique();

                    b.ToTable("Scoreboard", "public");
                });

            modelBuilder.Entity("Repositories.Entities.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("transaction_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<int>("AmountCoin")
                        .HasColumnType("integer")
                        .HasColumnName("amount_coin");

                    b.Property<int?>("BalanceAfter")
                        .HasColumnType("integer")
                        .HasColumnName("balance_after");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("PaymentId")
                        .HasColumnType("integer")
                        .HasColumnName("payment_id");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("integer")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("reference_type");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("TransactionId")
                        .HasName("Transaction_pkey");

                    b.HasIndex("AccountId");

                    b.HasIndex(new[] { "PaymentId" }, "Transaction_payment_id_key")
                        .IsUnique();

                    b.ToTable("Transaction", "public");
                });

            modelBuilder.Entity("Repositories.Entities.TryOnHistory", b =>
                {
                    b.Property<int>("TryOnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tryon_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TryOnId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("acc_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("img_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("TryOnId");

                    b.HasIndex("AccountId");

                    b.ToTable("TryOnHistory", "public");
                });

            modelBuilder.Entity("Repositories.Entities.UserProfileVector", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AccountId")
                        .HasName("User_Profile_Vector_pkey");

                    b.ToTable("User_Profile_Vector", "public");
                });

            modelBuilder.Entity("Repositories.Entities.UserReport", b =>
                {
                    b.Property<int>("UserReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_report_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserReportId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("post_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<int>("ReportTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("report_type_id");

                    b.HasKey("UserReportId")
                        .HasName("User_Report_pkey");

                    b.HasIndex("AccountId");

                    b.HasIndex("PostId");

                    b.HasIndex("ReportTypeId");

                    b.ToTable("User_Report", "public");
                });

            modelBuilder.Entity("Repositories.Entities.Wardrobe", b =>
                {
                    b.Property<int>("WardrobeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("wardrobe_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WardrobeId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("WardrobeId")
                        .HasName("Wardrobe_pkey");

                    b.HasIndex(new[] { "AccountId" }, "Wardrobe_account_id_key")
                        .IsUnique();

                    b.ToTable("Wardrobe", "public");
                });

            modelBuilder.Entity("ItemCategory", b =>
                {
                    b.HasOne("Repositories.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("Item_Category_category_id_fkey");

                    b.HasOne("Repositories.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("Item_Category_item_id_fkey");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Repositories.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Repositories.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Repositories.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Repositories.Entities.Comment", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithMany("Comments")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("comment_account_id_fkey");

                    b.HasOne("Repositories.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("comment_post_id_fkey");

                    b.Navigation("Account");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Repositories.Entities.Event", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Creator")
                        .WithMany("Events")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("Events_creator_id_fkey");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Repositories.Entities.EventWinner", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithOne("EventWinner")
                        .HasForeignKey("Repositories.Entities.EventWinner", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Entities.PrizeEvent", "PrizeEvent")
                        .WithOne("EventWinner")
                        .HasForeignKey("Repositories.Entities.EventWinner", "PrizeEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("PrizeEvent");
                });

            modelBuilder.Entity("Repositories.Entities.ExpertFile", b =>
                {
                    b.HasOne("Repositories.Entities.ExpertProfile", "ExpertProfile")
                        .WithOne("ExpertFile")
                        .HasForeignKey("Repositories.Entities.ExpertFile", "ExpertProfileId")
                        .IsRequired()
                        .HasConstraintName("Expert_File_expert_profile_id_fkey");

                    b.Navigation("ExpertProfile");
                });

            modelBuilder.Entity("Repositories.Entities.ExpertProfile", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithOne("ExpertProfile")
                        .HasForeignKey("Repositories.Entities.ExpertProfile", "AccountId")
                        .IsRequired()
                        .HasConstraintName("Expert_Profile_account_id_fkey");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Repositories.Entities.Follow", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Follower")
                        .WithMany("FollowFollowerNavigations")
                        .HasForeignKey("FollowerId")
                        .IsRequired()
                        .HasConstraintName("Follow_follower_id_fkey");

                    b.HasOne("Repositories.Entities.Account", "User")
                        .WithMany("FollowUserNavigations")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("Follow_user_id_fkey");

                    b.Navigation("Follower");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repositories.Entities.GroupUser", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithMany("GroupUsers")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("GroupUser_account_id_fkey");

                    b.HasOne("Repositories.Entities.Group", "Group")
                        .WithMany("GroupUsers")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("GroupUser_group_id_fkey");

                    b.Navigation("Account");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Repositories.Entities.Image", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithMany("Avatars")
                        .HasForeignKey("AccountAvatarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Repositories.Entities.Item", "Item")
                        .WithMany("Images")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Repositories.Entities.Post", "Post")
                        .WithMany("Images")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Account");

                    b.Navigation("Item");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Repositories.Entities.Item", b =>
                {
                    b.HasOne("Repositories.Entities.Wardrobe", "Wardrobe")
                        .WithMany("Items")
                        .HasForeignKey("WardrobeId")
                        .IsRequired()
                        .HasConstraintName("Item_wardrobe_id_fkey");

                    b.Navigation("Wardrobe");
                });

            modelBuilder.Entity("Repositories.Entities.MessReaction", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "AccountReact")
                        .WithMany("MessReactions")
                        .HasForeignKey("AccountReactId")
                        .HasConstraintName("MessReaction_account_react_id_fkey");

                    b.HasOne("Repositories.Entities.Message", "Message")
                        .WithMany("MessReactions")
                        .HasForeignKey("MessageId")
                        .HasConstraintName("MessReaction_message_id_fkey");

                    b.Navigation("AccountReact");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Repositories.Entities.Message", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithMany("Messages")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("Message_account_id_fkey");

                    b.HasOne("Repositories.Entities.Group", "Group")
                        .WithMany("Messages")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("Message_group_id_fkey");

                    b.HasOne("Repositories.Entities.Message", "ReplyToMessage")
                        .WithMany("InverseReplyToMessage")
                        .HasForeignKey("ReplyToMessageId")
                        .HasConstraintName("Message_replyToMessage_id_fkey");

                    b.Navigation("Account");

                    b.Navigation("Group");

                    b.Navigation("ReplyToMessage");
                });

            modelBuilder.Entity("Repositories.Entities.Model", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithMany("AccountModels")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Account_Models");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Repositories.Entities.Notification", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Sender")
                        .WithMany("Notifications")
                        .HasForeignKey("SenderId")
                        .IsRequired()
                        .HasConstraintName("Notification_sender_id_fkey");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Repositories.Entities.Outfit", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithMany("Outfits")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("Outfit_account_id_fkey");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Repositories.Entities.Package", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithMany("Packages")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("Package_account_id_fkey");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Repositories.Entities.Payment", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithMany("Payments")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("Payment_account_id_fkey");

                    b.HasOne("Repositories.Entities.Package", "Package")
                        .WithMany("Payments")
                        .HasForeignKey("PackageId")
                        .HasConstraintName("Payment_package_id_fkey");

                    b.Navigation("Account");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Repositories.Entities.Photo", b =>
                {
                    b.HasOne("Repositories.Entities.Message", "Message")
                        .WithMany("Photos")
                        .HasForeignKey("MessageId")
                        .HasConstraintName("Photos_message_id_fkey");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Repositories.Entities.PinnedMessage", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "AccountPinned")
                        .WithMany("PinnedMessages")
                        .HasForeignKey("AccountPinnedId")
                        .HasConstraintName("PinnedMessage_accountPinned_id_fkey");

                    b.HasOne("Repositories.Entities.Group", "Group")
                        .WithMany("PinnedMessages")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("PinnedMessage_group_id_fkey");

                    b.HasOne("Repositories.Entities.Message", "Message")
                        .WithMany("PinnedMessages")
                        .HasForeignKey("MessageId")
                        .HasConstraintName("PinnedMessage_message_id_fkey");

                    b.Navigation("AccountPinned");

                    b.Navigation("Group");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Repositories.Entities.Post", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithMany("Posts")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("Post_account_id_fkey");

                    b.HasOne("Repositories.Entities.Event", "Event")
                        .WithMany("Posts")
                        .HasForeignKey("EventId")
                        .HasConstraintName("Post_event_id_fkey");

                    b.Navigation("Account");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Repositories.Entities.PostVector", b =>
                {
                    b.HasOne("Repositories.Entities.Post", "Post")
                        .WithOne("PostVector")
                        .HasForeignKey("Repositories.Entities.PostVector", "PostId")
                        .IsRequired()
                        .HasConstraintName("Post_Vector_post_id_fkey");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Repositories.Entities.PrizeEvent", b =>
                {
                    b.HasOne("Repositories.Entities.Event", "Event")
                        .WithMany("PrizeEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Repositories.Entities.Reaction", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithMany("Reactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("reaction_account_id_fkey");

                    b.HasOne("Repositories.Entities.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("reaction_post_id_fkey");

                    b.Navigation("Account");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Repositories.Entities.RefreshToken", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithOne("RefreshToken")
                        .HasForeignKey("Repositories.Entities.RefreshToken", "AccountId")
                        .IsRequired()
                        .HasConstraintName("RefreshToken_account_id_fkey");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Repositories.Entities.Scoreboard", b =>
                {
                    b.HasOne("Repositories.Entities.Post", "Post")
                        .WithOne("Scoreboard")
                        .HasForeignKey("Repositories.Entities.Scoreboard", "PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Repositories.Entities.Transaction", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("Transaction_account_id_fkey");

                    b.HasOne("Repositories.Entities.Payment", "Payment")
                        .WithOne("Transaction")
                        .HasForeignKey("Repositories.Entities.Transaction", "PaymentId")
                        .IsRequired()
                        .HasConstraintName("Transaction_payment_id_fkey");

                    b.Navigation("Account");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Repositories.Entities.TryOnHistory", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithMany("TryOnHistories")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Repositories.Entities.UserProfileVector", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithOne("UserProfileVector")
                        .HasForeignKey("Repositories.Entities.UserProfileVector", "AccountId")
                        .IsRequired()
                        .HasConstraintName("User_Profile_Vector_account_id_fkey");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Repositories.Entities.UserReport", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithMany("UserReports")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("User_Report_account_id_fkey");

                    b.HasOne("Repositories.Entities.Post", "Post")
                        .WithMany("UserReports")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("User_Report_post_id_fkey");

                    b.HasOne("Repositories.Entities.ReportType", "ReportType")
                        .WithMany("UserReports")
                        .HasForeignKey("ReportTypeId")
                        .IsRequired()
                        .HasConstraintName("User_Report_report_type_id_fkey");

                    b.Navigation("Account");

                    b.Navigation("Post");

                    b.Navigation("ReportType");
                });

            modelBuilder.Entity("Repositories.Entities.Wardrobe", b =>
                {
                    b.HasOne("Repositories.Entities.Account", "Account")
                        .WithOne("Wardrobe")
                        .HasForeignKey("Repositories.Entities.Wardrobe", "AccountId")
                        .IsRequired()
                        .HasConstraintName("Wardrobe_account_id_fkey");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Repositories.Entities.Account", b =>
                {
                    b.Navigation("AccountModels");

                    b.Navigation("Avatars");

                    b.Navigation("Comments");

                    b.Navigation("EventWinner");

                    b.Navigation("Events");

                    b.Navigation("ExpertProfile");

                    b.Navigation("FollowFollowerNavigations");

                    b.Navigation("FollowUserNavigations");

                    b.Navigation("GroupUsers");

                    b.Navigation("MessReactions");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("Outfits");

                    b.Navigation("Packages");

                    b.Navigation("Payments");

                    b.Navigation("PinnedMessages");

                    b.Navigation("Posts");

                    b.Navigation("Reactions");

                    b.Navigation("RefreshToken");

                    b.Navigation("Transactions");

                    b.Navigation("TryOnHistories");

                    b.Navigation("UserProfileVector");

                    b.Navigation("UserReports");

                    b.Navigation("Wardrobe");
                });

            modelBuilder.Entity("Repositories.Entities.Event", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("PrizeEvents");
                });

            modelBuilder.Entity("Repositories.Entities.ExpertProfile", b =>
                {
                    b.Navigation("ExpertFile");
                });

            modelBuilder.Entity("Repositories.Entities.Group", b =>
                {
                    b.Navigation("GroupUsers");

                    b.Navigation("Messages");

                    b.Navigation("PinnedMessages");
                });

            modelBuilder.Entity("Repositories.Entities.Item", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Repositories.Entities.Message", b =>
                {
                    b.Navigation("InverseReplyToMessage");

                    b.Navigation("MessReactions");

                    b.Navigation("Photos");

                    b.Navigation("PinnedMessages");
                });

            modelBuilder.Entity("Repositories.Entities.Package", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Repositories.Entities.Payment", b =>
                {
                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Repositories.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Images");

                    b.Navigation("PostVector");

                    b.Navigation("Reactions");

                    b.Navigation("Scoreboard");

                    b.Navigation("UserReports");
                });

            modelBuilder.Entity("Repositories.Entities.PrizeEvent", b =>
                {
                    b.Navigation("EventWinner")
                        .IsRequired();
                });

            modelBuilder.Entity("Repositories.Entities.ReportType", b =>
                {
                    b.Navigation("UserReports");
                });

            modelBuilder.Entity("Repositories.Entities.Wardrobe", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
